name: Upload to COS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.SECRETID }}
        SECRET_KEY: ${{ secrets.SECRETKEY }}
        BUCKET: ${{ secrets.BUCKET }}
        REGION: ap-guangzhou
      run: coscmd config -a $SECRETID -s $SECRETKEY -b $BUCKET -r $REGION
    - name: Upload
      run: coscmd upload -rs --delete -f ./ / --ignore "./.git/*"
